[project]
name = "reroll-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anil Kulkarni" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
reroll-data = "reroll_data:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
